### ISSUE TITLE
SSR conflicts with Svelte NPM packages

### ISSUE THREAD

**Issue by abigtoe** [CaptainN/meteor-svelte-starter#1]
I'm trying out your starter kit (really impressive btw) but have run into a issue with sveltestrap and SSR. 

I've tried the following import statement :

import {Container} from 'sveltestrap';

but this is the error message in terminal:

> Error running template: Error: 'Container' is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

The Readme states that svelte packages need to be included in the meteor config section, and one must use Meteor 1.8.2 or higher.   I've done both but am still seeing the error message. 
The issue seems to be related to the SSR package, but I can't figure out how to force a recompile. Here is my package.json   (I removed  devDependencies for brevity's sake):

 
    "dependencies": {
        "@babel/runtime": "^7.6.0",
        "bcrypt": "^3.0.6",
        "clsx": "^1.0.4",
        "lodash.tonumber": "^4.0.3",
        "meteor-node-stubs": "^0.4.1",
        "simpl-schema": "^1.5.5",
        "svelte": "=3.6.7",
        "svelte-feather": "^1.1.2",
        "svelte-routing": "^1.4.0",
        "sveltestrap": "^3.1.1"
    },
    "meteor": {
        "mainModule": {
            "client": "client/main.js",
            "server": "server/main.js"
        },
        "testModule": "tests/main.js",
        "nodeModules": {
            "recompile": {
                "svelte-routing": [
                    "client",
                    "server"
                ],
                "svelte-loadable": [
                    "client",
                    "server"
                ],
                "svelte-feather": [
                    "client",
                    "server"
                ],
                "sveltestrap": [
                    "client",
                    "server"
                ]

**Comment by CaptainN** [comment]
I'm still a bit new to the svelte ecosystem - my guess is this doesn't work as expected because the `sveltestrap` package does not include a source distribution linked with the `svelte` key in it's `package.json`. The other packages (like `svelte-feather`) do include this key.

Does the same package work easily in a webpack/rollup build system? Do you have an example of such a build project (with SSR) I can look at to find compatibility settings?

**Comment by abigtoe** [comment]
@CaptainN I'm also quite new to the svelte world. I'll look around for a sveltestrap starter kit and get back to you.

**Comment by bestguy** [comment]
@abigtoe I've published a beta version that should correct this, based on https://github.com/sveltejs/component-template/blob/master/package.json (thanks for the tip @CaptainN)

Please try via installing:
`npm install sveltestrap@3.1.2-0`

**Comment by bestguy** [comment]
@abigtoe I confirmed this does work, however you must import the source directly, for example:

```javascript
import Card from 'sveltestrap/src/Card.svelte';
```

Please see https://github.com/bestguy/sveltestrap/issues/48 for details.  I'm not sure if there's anything you can do in template to correct this @CaptainN so feel free to close.

**Comment by CaptainN** [comment]
Thanks for the speedy work! :-)
