### ISSUE TITLE
Send status code 404

### ISSUE THREAD

**Issue by castasamu** [CaptainN/meteor-svelte-starter#6]
@CaptainN Nice work!

But if I would to implement SSR to send
`sink.setStatusCode(404); `
how can I pass if the page not found?

I try do in this way (obviously after make the component E404.svelte)
```javascript
if(loadableHandle.toEJSON().includes('E404.svelte')) {
     sink.setStatusCode(404);
}
```
but in this way I have some issue when i go in a page that not exists like /pages/about-us-wrong and slug about-us-wrong not exists.

Thanks for all and nice work again.
I want to apologize for my bad english. :(

**Comment by castasamu** [comment]
With react it's easy to do that. Just set staticContext...

**Comment by CaptainN** [comment]
I wonder if you could set some kind of global state to track that? In React you could create a provider which contains a setter and a value for is404 or something similar. I'm not as familiar with Svelte yet (and may not get up to snuff sadly, given a lack of time), but there is probably something similar.

**Comment by CaptainN** [comment]
Actually, the answer is partly in the repo code. In `/server/ssr.js` we pass in a `loadableHandle` to the App.svelte component, which is a prop set up to receive a value. We could do the same for the `sink` object, and do whatever logic, then set 404 that way.
