### ISSUE TITLE
Does not work on Android

### ISSUE THREAD

**Issue by HassanYA** [CaptainN/meteor-svelte-starter#7]
When running on android (using "meteor run android"), following error appears in console:
`Uncaught (in promise) TypeError: Class constructor SvelteComponentDev cannot be invoked without 'new'`

**Comment by CaptainN** [comment]
I'm afraid that's a bit outside of my understanding, and I probably won't be much help to you. My guess is it's either some kind of `ecmascript` setting conflict with Cordova, or a problem with the way `svelte-compiler` is caching its built files.

One thing I can suggest to test the build-cache guess, try doing a `meteor reset` and then run on Android again right after

**Comment by HassanYA** [comment]
nope, does not solve it
you were my last hope... meteor forums lat me down

**Comment by CaptainN** [comment]
I'd probably reach out on the `meteor-svelte` repo. This sounds like something they should be aware of: https://github.com/meteor-svelte/meteor-svelte

**Comment by HassanYA** [comment]
Yes, I think I am gonna head over there and annoy them. Thanks captain
